systems:
  - id: amvic
    name: South East Energy Agency (AMVIC)
    airtableId: appsOHJyDxhPrHyxc
  - id: mobble
    name: Inhout Mobble
    airtableId: app25JFkKVKKEt5io
  - id: swift
    name: WikiHouse Swift
    airtableId: appGlzQcCZpDNRFsE
  - id: holz100
    name: HOLZ100
    airtableId: appzG3plVRqgH6c5f
